/**
 * Exports the contract ABIs (and the factory/implementation bytecode for deploy-factory) from
 * Foundry's output into packages/agent/src/abi.ts as `as const` values for viem.
 * Run after `forge build` (root `npm run build:contracts` does both).
 */
import { readFileSync, writeFileSync } from 'node:fs';

const out = (file: string, name: string) =>
  JSON.parse(readFileSync(new URL(`../contracts/out/${file}/${name}.json`, import.meta.url), 'utf8')) as {
    abi: unknown[];
    bytecode: { object: string };
  };

const wallet = out('PolicyWallet.sol', 'PolicyWallet');
const factory = out('PolicyWalletFactory.sol', 'PolicyWalletFactory');

const body = `// Generated by scripts/export-abi.ts from contracts/out. Do not edit by hand.
export const policyWalletAbi = ${JSON.stringify(wallet.abi, null, 2)} as const;

export const policyWalletFactoryAbi = ${JSON.stringify(factory.abi, null, 2)} as const;

export const policyWalletBytecode = '${wallet.bytecode.object}' as const;

export const policyWalletFactoryBytecode = '${factory.bytecode.object}' as const;
`;
writeFileSync(new URL('../packages/agent/src/abi.ts', import.meta.url), body);
console.log(`✓ ABIs exported: PolicyWallet (${wallet.abi.length} items), PolicyWalletFactory (${factory.abi.length} items)`);
